spring:
  application:
    name: ddd-sample
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    orm: META-INF/orm.xml
    open-in-view: false
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password: 
    driver-class-name: org.hsqldb.jdbcDriver
# Logging Configurations
logging:
  file: myfile.log
  path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%thread] %-5level %logger{35} - %msg%n"